# Site Settings
title: "Nicolas Jouanno"
headline: "Père, développeur et sportif. Je documente notre vie de famille nomade en van à travers l’Europe."
url: "https://www.nicolasjouanno.com"

# author
author:
  name: "Nicolas JOUANNO DANIEL"
  location: "Pontivy, Bretagne, France"
  country: "France"
  email: "contact@nicolasjouanno.com"
  web: "https://nicolasjouanno.com/about.html"
  certifications_folder: "https://drive.google.com/open?id=14JiH6ytQDige_iIOZPUUYq-W38VPaWTo"

  # social
  webmention: "https://webmention.io/www.nicolasjouanno.com/webmention"
  handle: "@bynicolasjd"
  bitbucket:
  codepen:
  dribble: "https://dribbble.com/nicolasjouanno"
  flickr:
  facebook:
  foursquare:
  github: "https://github.com/jn-prod"
  gitlab:
  keybase:
  instagram: "https://www.instagram.com/bynicolasjd/"
  lastfm:
  linkedin: "https://www.linkedin.com/in/nicolasjouanno/"
  mediumcom: "https://medium.com/@nicolasjouanno"
  pinterest: "https://fr.pinterest.com/nicolasjouanno/"
  soundcloud: "https://soundcloud.com/nicolasjouanno"
  stackoverflow: # "123456/username" (the last part of your profile   url, e.g. https://stackoverflow.com/users/123456/username)
  steam: # "steamId" (the last part of your profile   url, e.g. https://steamcommunity.com/id/steamId/)
  strava: "https://www.strava.com/athletes/njouanno"
  substack: "https://bynicolasjd.substack.com/welcome"
  tumblr:
  twitter: "https://x.com/byNicolasJD"
  wikipedia: "https://fr.wikipedia.org/wiki/Nicolas_Jouanno"
  youtube: "https://www.youtube.com/channel/UCcvmBtY40bompka9CkjrmLg"

# collections
collections:
  events:
    output: true
    permalink: /events/:slug.html
    sort_by: start

defaults:
  - scope:
      path: "_events"
      type: "events"
    values:
      layout: "event"

# Outputting
lsi: false
safe: true
permalink: /:title:output_ext
paginate: 12
paginate_path: /stories/latest/page:num/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-archives
  # - jekyll-minifier

whitelist:
  - jekyll-paginate

# Archives
# jekyll-archives:
#   enabled:
#    - categories
#  layout: archive
#  permalinks:
#    category: '/:name/'
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Minification
# jekyll-minifier:
#   exclude: 'feed.xml'

# Other
markdown: kramdown
highlighter: rouge
future: false
sass:
  style: compressed
